# Generated by Django 2.2.4 on 2019-08-06 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_subscriber_date_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.City'),
        ),
    ]
