# Generated by Django 2.2.4 on 2019-08-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_auto_20190806_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='zip',
            field=models.CharField(default='00000', max_length=5),
            preserve_default=False,
        ),
    ]
