# Generated by Django 2.2.4 on 2019-08-08 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_city_zip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='rank',
        ),
    ]
